export const signin = async (req, res) => {
  try {
    //this is where the logic code will go
  } catch (error) {
    res.status(500).json({ message: "Something went wrong!" });
  }
};
